### ISSUE TITLE
Where are the help files?

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShellGetv2#1]
In Windows PowerShell 5.0, the PowerShellGet module directory has an en-US directory with 2 XML help files:
PSGet.psm1-help.xml
PSModule.psm1-help.xml

They are not in PowerShell 6, so there's no help for the functions or the module.

**Comment by bmanikm** [comment]
@juneb Due to a backward-compatibility reason (PSGet.psm1 got renamed to PSModule.psm1), PowerShellGet will have a single help file with PSGet.psm1-help.xml.  Update-Help -Module PowerShellGet should update the help file under en-US directory. There is a known issue in Update-Help with https HelpInfoUri --> https://github.com/PowerShell/PowerShell/issues/1918. To workaround that issue, we can update the PowerShellGet's HelpInfoUri to http value.

**Comment by juneb** [comment]
Thanks, Mani. I actually reported that help file issue. :)
Will the help files be added to this GitHub project or to PowerShell-Docs?

**Comment by pcgeek86** [comment]
> To workaround that issue, we can update the PowerShellGet's HelpInfoUri to http value.

Won't that open up PowerShell to man in the middle (MITM) attacks? @bmanikm

**Comment by juneb** [comment]
Actually, I wrote a separate bug, because Update-Help requires http and won't accept https value.

**Comment by bmanikm** [comment]
@pcgeek86 I agree with you on MITM attacks but as @juneb mentioned above Update-Help requires http.

@juneb PowerShellGet documentation is available in PowerShell-Docs (https://msdn.microsoft.com/en-us/powershell/gallery/psget/overview)

**Comment by pcgeek86** [comment]
@bmanikm What is the work effort to get `Update-Help` to support HTTPS? This doesn't seem like something that should be very hard to fix. I'd classify this a high priority bug.

@juneb Which bug did you file about HTTPS for `Update-Help`?

**Comment by bmanikm** [comment]
Fixed in https://github.com/PowerShell/PowerShellGet/pull/82
