### ISSUE TITLE
[Issue-Question] How do I download from gallery when Package Manager not allowed?

### ISSUE THREAD

**Issue by ghost** [PowerShell/PowerShellGetv2#123]
Issue created by PSGallery team, ported from Twitter conversation: https://twitter.com/texmandie/status/861932115495190528 

## Expected Behavior
---Information needed from customers---

## Current Behavior

Concern raised about use with PS v3, which should be possible using https://www.microsoft.com/en-us/download/details.aspx?id=51451

---Information needed from customers---

## Possible Solution
Suggestions include installing / using Nuget directly, but team concerned about user experience.

## Your Environment

```PowerShell

> $PSVersionTable

> Get-Module

> Get-Module -ListAvailable PowerShellGet,PackageManagement

> Get-PackageProvider

> Get-PackageProvider -ListAvailable
```

**Comment by RamblingCookieMonster** [comment]
Some quick thoughts on alternatives currently available:

* PowerShellGet and PackageManagement should be available for PowerShell 3 - this seems to be the plan, based on [this bit](https://www.microsoft.com/en-us/download/details.aspx?id=51451) being linked from the Gallery

* Nuget is a viable option for anyone using the commandline.  It's simple to deploy (portable executable) and has what is needed to both download, and install a module from the gallery or an internal feed.  A wrapper function might be nice.

* The gallery can be queried, and zipped modules can be downloaded [without much effort](https://gist.github.com/Jaykul/9a810bac8584dd654cf9b0cffe6426eb) - again, a wrapper with a bit more functionality would be nice, but then you run into... why that, rather than PowerShellGet.

* Folks can construct URLs and manually download zipped files if they desire

* A large portion of PowerShell modules can be directly downloaded via GitHub (very few have build processes that change things, although this may change)

So!  If we look at Amanda's comment, I agree that you might simplify adoption for a small subset - folks who both know there is a gallery (good), and cannot use PowerShellGet, even on a server that simply pulls this down to a nuget feed, [file share](http://community.idera.com/powershell/powertips/b/tips/posts/creating-your-private-powershellget-repository) based repo, or heck... just a standard file share that necessary systems can hit.

Maybe more content and tooling around defining what modules and versions to pull down would help?  I'm struggling to see a scenario where you couldn't either use the tools (sysadmin systems), or at the very least, pull from a synchronized source, even if that was a filesystem (prod/test/whatever systems).

* _I want to experiment with module XYZ quickly_: Use any system that has PowerShellGet, use nuget, etc.
* _I want sysadmins to be able to download modules XYZ and ABC_: Use whatever tools work for you to download these modules to a central spot that other folks can get to

etc.

Missing anything?  I'm somewhat concerned about the potential negative consequences of including a GUI that makes it easy to ignore the appropriate tools, workflows, and module versions... I also think there are more pressing issues and feature requests, that don't have any workarounds, or the potential negative effects...

Cheers!

**Comment by Jaykul** [comment]
It only takes a handful of lines of code to **find** and download a module from the gallery by name _without_ PowerShellGet. There are _a **lot**_ of features which we _need_. This isn't one.

You can send people to [this gist](https://gist.github.com/Jaykul/9a810bac8584dd654cf9b0cffe6426eb) for a _slightly_ nicer version including separate search, but here's the simple version:

```posh
filter Save-Module {
    param (
        [Parameter(ValueFromPipelineByPropertyName=$true, Mandatory=$true)]
        [string]$Name,
        [string]$Path = $pwd
    )
    $searchUrl = "https://www.powershellgallery.com/api/v2/Packages?`$filter=Id eq '$name' and IsLatestVersion"
    foreach ($module in Invoke-RestMethod $searchUrl) {
        $OutFile = Join-Path $Path ($module.title.'#text' + $module.properties.version + '.nupkg')
        Invoke-WebRequest $module.Content.src -OutFile $OutFile
        Get-Item $OutFile
    }
}
```

**Comment by potatoqualitee** [comment]
You guys have such well thought-out posts. I've got a lot of feelings ;)

Basically, I've seen the successes of shortlinks and a /zip that grabs the latest version of the .nuget and sends the filename as {modulename}.zip would be tremendously helpful. We'd help get the word out on it.

I understand that in an ideal world, PowerShellGet and PackageManagement would be the answer, but I like to give people a simple solution first, then give them time to justify the 'proper' solution. Eventually, I imagine, they'll get frustrated with version control and seek out a better solution and end up using PSGet and PM.

The gist is really nice, but it's a lot of lines. A single line like `Invoke-WebRequest ps.gallery/sqlserver -Out sqlserver.zip` (and, perhaps, a corresponding longlink like powershellgallery.com/sqlserver/zip) would help ease employees from restrictive orgs into getting modules from the gallery via PS. This could be accomplished using simple HTTP redirection at ps.gallery since the package location already exists at `https://www.powershellgallery.com/api/v2/package/sqlserver`

I'd do it myself but .gallery domains are $72 year and I've maxed out my domain budget D:

Ultimately, the reason why I'm advocating for this is because zips are understandable and straightforward and this seems like an easy way to help people who are in restrictive environments. Shortlinks are memorable and easy.

**Comment by ghost** [comment]
Good input, but maybe missing clarification. Is the core problem a combination of the package is not obviously a .ZIP file, and the acquisition method is via a REST API? If so, then would a blog as described between @Jaykul and @potatoqualitee be sufficient? 

@RamblingCookieMonster - One point to add is that PowerShellGet IS the wrapper around those functions, nothing more. NuGet is a zip file with extra structured (meta-)data that makes it easier to build filters around the zip package, and to build installers for the various kinds of things put into the zip. PowerShellGet wraps NuGet, creates an installer that works well for PowerShell modules.

**Comment by Jaykul** [comment]
I think it was 6 year ago when I reached my limit on the number of times I was willing to explain to people that there is nothing wrong with my module, they've just _unzipped it in the wrong place._

#### Zips are _not_ a straightforward way of shipping modules

Unpacking a module in the right place requires an understanding of path environment variables and how modules are built (other wise you end up with your psd1 either one level too deep, or not deep enough). For that reason, I'm *strongly* opposed to providing any of these methods of getting a .zip -- even if it was just a link that renames the nupkg at download time. *we* (the community) would spend another 10 years *"supporting"* people who can't figure out an atom feed, and then need to figure out where to unzip the module to, and how to distribute it across their enterprise.

Who are these hypothetical people who _can't_ use a **Microsoft** module (PowerShellGet), but need to have an easier time to download **third-party** modules from the gallery? I really can't believe there are enough organizations where this is useful to make it worth doing -- teams that have the skills to do the install but not to figure out the 5 lines of code to fetch it, and work in a place where they can use third-party modules, but not Microsoft modules?

**Comment by potatoqualitee** [comment]
> Zips are not a straightforward way of shipping modules

Fair enough. That's why I offer **both** [dbatools.io/zip](https://dbatools.io/zip) _and_ [dbatools.io/in](https://dbatools.io/in) which allows people to run 

`Invoke-Expression (Invoke-WebRequest -UseBasicParsing https://dbatools.io/in)`

This unzips the zip and places the module in their module directory. I've spent 0 time supporting module placement because I've done my best to reduce barriers to installation and use.

The SQL Server Reporting Services team even used the script as a base in their own module for people who don't have access to the Gallery. Several people have mentioned how much they appreciate how easy it is to install dbatools - and most people are using the non-Gallery one-liner to do it (~42% are running PS5+).

> Who are these hypothetical people who can't use a Microsoft module (PowerShellGet), but need to have an easier time to download third-party modules from the gallery?

Me! Back in 2011. I didn't understand modules vs scripts. It took me working with PowerShell extensively to get what's going on. Until then, I would have wanted a one-liner to just do everything for me. That's one of the reasons I made sure dbatools came with an easy installer.  

I think it's important to focus on simple usability for beginners and people who don't have the experience that we do. I've learned that from the SQL Server community. PowerShell is scary enough as it is. Once people can do things with a one-liner, like the installer (both the Gallery and the script), they get excited and are a wee bit less intimidated. It's a good investment.

@JKeithB - I don't think a single blog post is the answer. I think an easy-to-remember URLs that enable one-liners are important.

**Comment by Jaykul** [comment]
@potatoqualitee you're suggesting an installer script that makes things a one-liner -- the PowerShell Gallery has one of those: the PowerShellGet module. To make it easy for people to install, it's wrapped in an msi that any beginner can click through.

>Me! Back in 2011... I would have wanted a one-liner to just do everything for me.

So you want this _not_ because of some prohibition against installing the PowerShellGet module, but because installer _scripts_ are perceived as easier than using a module? The more we talk, the more convinced I am that this is a **terrible** idea.

We **do not** need to make it easier for people to write scripts to install individual modules. 

We **do** need to get the whole world to install the _signed_, authentic, safe PowerShellGet module that supports installing modules with dependencies, name collision checks, cabinet signature checks and more.

As a side point ...

### `Invoke-Expression (Invoke-WebRequest ...)` is considered harmful.

A one-liner should be `Install-Module Pansies`. `Invoke-Expression` is **just not safe**, nobody should be encouraging people to just _run code off the internet_.

**Comment by kilasuit** [comment]
@potatoqualitee - I personally can't see the real benefit of having yet another URL that needs to be constantly updated when there are new modules uploaded (like imagine the manual workload, unless automated ofc)

However what I think that @amandadebler was meaning is that the PowerShell Gallery should have a button that says `Download Now`

**Comment by potatoqualitee** [comment]
@kilasuit - it would be an auto redirector. Basically, a shortlink to the longer API URL. Nothing to keep track of. If a package doesn't exist, the shortlink will just hit a 404.

@Jaykul - I understand where you're coming from. Both of our positions are valid - yours caters to security and being proper, mine to widespread adoption and reality. And really, my support of each argument will vary, depending on the day ;)

**Comment by amandadebler** [comment]
Yup, @kilasuit is right - I want a 'Download Now' button for my colleagues who don't fully understand what a module is yet, much less how to make Invoke-WebRequest work with our proxy (the difficulty in that might actually be an argument in its favor!)

**Comment by potatoqualitee** [comment]
With that, we return to the issue @Jaykul mentioned of module placement and support (which is why I was in favor of iex/iwr). There should perhaps be a note in the Download Now box that suggests where to put it. GitHub has a nice way of displaying more info.

![image](https://cloud.githubusercontent.com/assets/8278033/26058735/73575b74-397f-11e7-935d-201841e279bf.png)

**Comment by ghost** [comment]
Thanks, everyone, for helping explain the asks. I believe we have the information to close this particular thread, and open separate issues. I am going to try to summarize what's here (without evaluating) so that we get the issues opened properly. I believe this comes down to:

- Have a "download now" button that puts a zip somewhere on the user's system. Primary reasons are:  support customers who are not using PowerShell frequently; provide easier route for people going through proxies. Primary concern raised are that this will not properly install a module or script, & the user must do so themselves. 
- Create an article that explains how to download something from the Gallery without using PowerShellGet, how to unzip that, and install it properly. Primary reason is supporting users who have PSv3. 

If I missed something, please reply. Otherwise I'll open the 2 issues & close this thread with appropriate pointers.

**Comment by potatoqualitee** [comment]
Thanks, Keith.

> support customers who are not using PowerShell frequently

I don't think there's any issue with frequency.  `Install-Module sqlserver` is the actually the easiest way for people who are new to PowerShell to install modules. My concerns are about people who don't have access to PowerShellGet and thus can't use the easiest way.

> provide easier route for people going through proxies

The proxy issue came up, but I don't believe this is an issue as proxies are supported by both PowerShellGet and by Invoke-WebRequest.

> Primary reason is supporting users who have PSv3.

I also don't think PSv3 is an issue necessarily, but rather, the inability to get PowerShellGet for any reason.

Otherwise, looks great!

**Comment by ghost** [comment]
@potatoqualitee - Thank you, good clarifications. 
Any others?

**Comment by kilasuit** [comment]
PackageManagement works (or at least has been explained & in my experience it does) on PSv3

I don't know/understand how this can be mis-read to mean anything else

![image](https://cloud.githubusercontent.com/assets/6355225/26168427/ee3e0668-3b31-11e7-9339-dfe7e64f0516.png)

Even moreso when I created this script https://github.com/kilasuit/PoshFunctions/blob/Dev/Scripts/Install-PowerShellPackageMangement.ps1 and blogged about it at https://blog.kilasuit.org/?p=391 (although my blog is currently offline)

It's Psv2 and those v3/v4/v5 machines that are locked down or actually more commonly, that are air gapped, that are the issue the @amandadebler was trying to point out about I believe.

Re this @JKeithB 
> Have a "download now" button that puts a zip somewhere on the user's system. Primary reasons are: support customers who are not using PowerShell frequently; provide easier route for people going through proxies. Primary concern raised are that this will not properly install a module or script, & the user must do so themselves.

A blog post or telling users to how to correctly do things will be a help that must be linked to by the Download Now button

**Comment by potatoqualitee** [comment]
LOL I'm entertained that my comments are so controversial. Merry Christmas everyone! 🎁 Has there been any progress within the team to solve or close this issue?

Thanks,
Chrissy

**Comment by potatoqualitee** [comment]
Also, I had to go the manual route for PowerShellGet last week and that was a pain. The information is all over the place since the prominent link provided to **PowerShellGet** actually requires PowerShellGet in the first place.

![image](https://user-images.githubusercontent.com/8278033/34342798-c33ecf2c-e9bb-11e7-92a2-6179403d2859.png)

It'd be 💣 if there could be two emphasized links - one for 5.0 and then the deemphasized one for v3/4. Make them both big ol blue boxes and then show people how to get their current PowerShell version.

**Comment by potatoqualitee** [comment]
Just noticed that @kilasuit's screenshot varied from mine. It's closer to my request than the current state. However, I'd say that `WMF` only means something to people who understand PowerShell. It's too technical (sans the win10 promot, glad to see it's gone). How about:

`Install PowerShell Gallery access (PowerShellGet) on PowerShell 3 & 4`
`Update PowerShellGet for PowerShell 5+`
`Don't know your current version? Type $PSVersionTable to find out.`

The landing page was not written for people new to PowerShell and I think that's a lost opportunity 🌮

**Comment by ghost** [comment]
@potatoqualitee - thanks for the updates, there are multiple topics so responding in reverse-chron order:
- The explanation on our (over) use of vernacular helps a bunch. That is definitely something we try to avoid. And yes, the front-page UI changed since May, in an attempt to make it more simple.  
- On manual installation, we can write the info, have 2 questions: why did you need to do full manual install (helps with starting point for topic), and is it for some specific Windows version? 
- We don't have the "download now" button as a high-pri item right now. I'm going to draft & publish our focus areas by end of January, which will explain why (I hope).

**Comment by jakerobinson** [comment]
I have a growing percentage of users speaking up with this issue, and I am happy to share my observations. They are generally highly regulated organizations, and their datacenter environments do not have access to the Internet, so offline install is required. They have to `Save-Module` from their laptop, then copy many folders to a USB drive or internal network share, then they must put those into the modulepath of the offline machine. Most of these offline machines are running 3.0, and their laptops are running 5.1. There's an issue related to this in #171.

Here are some other common challenges I have seen:

1. Cannot update PowerShellGet and package providers since they do not have admin rights on their machines.

2. powershellgallery.com is not trusted for downloads. This is a big one. I can't force them to trust the domain.

3. offline install of many module folders is cumbersome, would prefer a .zip since you can at least get a hash on a single file to make sure it hasn't changed along the way.

4. An internal PowerShell gallery could be a solution, but there are not a whole lot of resources on the web for running and maintaining one.

**Comment by Jaykul** [comment]
Two thoughts re. @jakerobinson's needs:

1. The code I mentioned in [my earlier comment](#issuecomment-300673472) downloads the packages as .nupkg files. 
2. You can also use nuget to install (or restore) and keep the nupkg files. 

At work, we recently started using a packages.config file and `nuget restore` to download a whole list of modules at once and then `nuget push` them to our internal gallery:

```posh
# If you don't have nuget.exe, get it:
iwr https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe

# If you don't have a list, make one
'<packages>
  <package id="Configuration" version="1.2.0" />
  <package id="Pansies" version="1.2.1" />
  <package id="PowerLine" version="3.0.3" />
</packages>' > packages.config

# Fetch them all
.\nuget restore .\packages.config -PackagesDirectory unpack -PackageSaveMode nupkg -Source https://www.powershellgallery.com/api/v2/

# Collect all the nupkg
mkdir repository
mv unpack\*\*.nupkg repository

# Throw the unpacked modules away, because I don't need the loose files
rm unpack -recurse
```

Now I can use that `repository` folder as a PSPackageSource for installing within the network...

I'd love if the `PackageSaveMode` option was on the `Save-Module` command -- I can actually `Install-Module` from my local copy of the nupkg, whereas the current `Save-Module` doesn't help as much in this regard.

**Comment by bergmeister** [comment]
I wrote the following simple helper to optionally install/import modules on mixed systems that have WMF4/5. It is very simple and just dumps the module in the current folder (because in my case, it will get cleared up as part of the test teardown)

```` PowerShell
function InstallAndImport-ModuleIfNeeded {
    [CmdletBinding()]
    Param($Name)

    if (-not (Get-Module -ListAvailable ${Name})) {
        # PowerShellGet only shipped in WMF 5
        if (-not (Get-Module -ListAvailable PowerShellGet)) {

            Invoke-WebRequest https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe
            & (Join-Path $PSScriptRoot 'nuget.exe') install ${Name} `
                -Source https://www.powershellgallery.com/api/v2/ `
                -OutputDirectory (Join-Path $PSScriptRoot ${Name})
            Remove-Item -Path (Join-Path $PSScriptRoot 'nuget.exe') -ErrorAction Ignore
            (Get-ChildItem "${Name}\*\${Name}.psd1") | Import-Module
        }
    }
    else {
        Install-Module ${Name}
        Import-Module ${Name}
    }
}
````

**Comment by jtmoree-github-com** [comment]
Hi all,   I just came across this thread as I wanted to get the latest version of invoke-sqlcmd2.    After google took me to this page:  https://www.powershellgallery.com/packages/Invoke-SqlCmd2/1.6.4   I thought.  Ok good.  I want to try this.  So I followed the 'How to Download' link.  That's when the real frustration started.

https://www.powershellgallery.com/packages/Invoke-SqlCmd2/1.6.4/Download

This page does not mention powershellget or nuget or anything that would allow me to use the example commands.  It speaks as if my system is already setup with these tools which would almost never be the case for a new user who just came across this module, no?  Is this a page maintained by powershellgallery or by this invoke-sqlcmd2 project?

If this is a page maintained by someone on this thread, please add the missing information.  How about this?

"The short answer is, there is no download link because there is a faster way to download and install from the PowerShell prompt using the powershellget module https://docs.microsoft.com/en-gb/powershell/gallery/installing-psget." 

If this is a page maintained by the powershell gallery site I will try to get this request forwarded to them.  

Thank you for paying attention.

**Comment by ghost** [comment]
@jtmoree-kahalamgmt-com - good feedback and thank you. I guess we did make the (false) assumption that everyone came through the home page where the instructions live. 
Definitely something we need to fix.

**Comment by ghost** [comment]
For anyone following this thread, please check out the new preview.powershellgallery.com. We have added the manual download button, with initial documentation linked from the FAQs (which is linked from the bottom of each page in the Preview site).

**Comment by SydneyhSmith** [comment]
Closing as it appears this issue has been addressed in the latest powershellgallery.com please respond with the remaining issues if you do not feel this issues has been resolved.
