### ISSUE TITLE
General Improvements to fit in with PowerShell best Practices

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShellGetv2#13]
A few things 
- [ ] - as mentioned in #12 we need to get the tests upto a reasonable level _before_ we start adding new/updated/fixed functionality into the code base to enable us not to break things going forward
- [x] - all PR's must be also tested on downlevel OS environments & downlevel PS environments too 
- [ ] - PR's must also have chance to be validated by community members as well as PSTeam 
- [ ] - Verb-Noun should be followed even for internal/private functions using correct verbs
- [ ] - 1 PR to 1 Issue - #12 should not have been combining fixes from 2 issues and should have been 2 PR's

This isn't a full list of things that _I think_ need to be prioritised but would make a good starting point

**Comment by bmanikm** [comment]
Thanks @kilasuit!
Yes, we are working on getting the complete test suite into this git repo. There are many tests for PowerShellGet, all of them were written in Lite3 (MSFT internal test infra). I am currently working on porting them to Pester-based tests so that they can be added to the PowerShellGet git repo. Yes, we run all PowerShellGet tests on all supported platforms.

**Comment by edyoung** [comment]
The Pester-based tests are now included. While I won't claim everything on this list is addressed I don't think the issue as listed is really actionable.
