### ISSUE TITLE
Cannot republish a module with the same version number

### ISSUE THREAD

**Issue by mcvic1rj** [PowerShell/PowerShellGetv2#136]
## Expected Behavior
When publishing a module with -force switch, it should be expected that the module will publish even if it already exists in the repository.

## Current Behavior
An error is thrown: ModuleVersionIsAlreadyAvailableInTheGallery

## Possible Solution
Update line 1215 of PSmodule.psm1 from
                if($currentPSGetItemInfo.Version -eq $moduleInfo.Version)
to
                if(-not $force -and $currentPSGetItemInfo.Version -eq $moduleInfo.Version)

## Steps to Reproduce (for bugs)
Attempt to publish a module twice with the following commands
Publish-Module -Path $path -NuGetApiKey $apikey -Repository $repo
Publish-Module -Path $path -NuGetApiKey $apikey -Repository $repo -force

## Context
Trying to republish a module without incrementing a version number due to a minor change.

## Your Environment
Using PowershellGet version 1.1.3.1

> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by bmanikm** [comment]
@mcvic1rj PowerShell Gallery doesn't allow republish of the same version. You should unlist this version in the gallery and publish a new version after incrementing.

**Comment by mcvic1rj** [comment]
@bmanikm Sorry about that. I didn't know this was by design. I was basing this off our our internal NuGet repo which allows overwriting.

-
Ryan

**Comment by midacts** [comment]
@bmanikm How do you unlist a previous version?
(I only care about an internal publish of a module - not publishing to powershellgallery.com)

**Comment by bmanikm** [comment]
Documentation on unlisting a published version on PowerShell Gallery --> https://docs.microsoft.com/en-us/powershell/gallery/psgallery/psgallery_unlist_items.

If you are working with your internal or custom repositories, please consider deleting the existing version then re-publish the same version.

**Comment by midacts** [comment]
"To unlist your item, visit the item details page and select 'Delete Item'.
Uncheck the 'Listed' checkbox, and click Save."

I have a internal nuget feed. I don't know if it has this option but I will
check in the morning.

How can you delete the current version?
There isn't a cmdlet for that.

On Sep 25, 2017 6:12 PM, "Manikyam Bavandla" <notifications@github.com>
wrote:

Documentation on unlisting a published version on PowerShell Gallery -->
https://docs.microsoft.com/en-us/powershell/gallery/
psgallery/psgallery_unlist_items.

If you are working with your internal or custom repositories, please
consider deleting the existing version then re-publish the same version.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/PowerShell/PowerShellGet/issues/136#issuecomment-332028996>,
or mute the thread
