### ISSUE TITLE
Install-Module should be installing to parent of $PSHOME for PSCore6

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShellGetv2#175]
Currently, `Install-Module` puts modules into a `Modules` folder under $PSHOME.  The problem is that when 6.0.0-beta.7 is upgraded to 6.0.0-beta.8, all the modules are "gone" since they are in the 6.0.0-beta.7 folder.  They should probably be installed in ${env:programfiles}\PowerShell\Modules which is already in $env:PSModulePath

**Comment by lwsrbrts** [comment]
There's two options I think. My preferred option is at the bottom.

I think changing one line could achieve this but have a question in respect of x86 versus x64 versions of PowerShell. Does the x86 version of PowerShell Core install to C:\Program Files (x86)\PowerShell\ on an x64 machine and C:\Program Files\PowerShell on an x86 machine?

If so, what would the use of $env:ProgramFiles return in either case?

If a user on an x64 machine installed x86 PowerShell (possible?) any use of $env:ProgramFiles would result in issues for them wouldn't it? I know these are questions I could answer myself by JFDI but if someone can answer without me building an example, that would be preferable.

I've commented the original line and added in the new code underneath it (in the else) but if processor architecture and version of PowerShell installed is going to play a part here, it probably needs to be accommodated. I expect some additional if, else within the `else` using $env:PROCESSOR_ARCHITECTURE if so.

```powershell
if($script:IsInbox)
{
    $script:ProgramFilesPSPath = Microsoft.PowerShell.Management\Join-Path -Path $env:ProgramFiles -ChildPath "WindowsPowerShell"
}
else
{
    #$script:ProgramFilesPSPath = $PSHome
    $script:ProgramFilesPSPath = Microsoft.PowerShell.Management\Join-Path -Path $env:ProgramFiles -ChildPath "PowerShell"
}
```

The alternative is that $PSHOME is still used and its parent calculated instead. The reason this is preferred is because if the user were to install PowerShell to some other location on disk (assuming they get that option?) then the use of $env:ProgramFiles for PSCore might not be where the install is or where the user wants Modules to go.

```powershell
if($script:IsInbox)
{
    $script:ProgramFilesPSPath = Microsoft.PowerShell.Management\Join-Path -Path $env:ProgramFiles -ChildPath "WindowsPowerShell"
}
else
{
    #$script:ProgramFilesPSPath = $PSHome
    $script:ProgramFilesPSPath = Microsoft.PowerShell.Management\Split-Path -Path $PSHOME
}
```

These are at line: 29 in the module so very early on.

Any comments welcome.

**Comment by lwsrbrts** [comment]
Answering my own question without giving anyone enough time to respond...

Installing PowerShell x86 on an x64 machine puts PowerShell, by default in `C:\Program Files (x86)\PowerShell` however both `$env:ProgramFiles` AND `${env:ProgramFiles(x86)}` from the PSCore6 shell returns `C:\Program Files (x86)`, so that issue goes away.

However the user does have the option to install PowerShell wherever they please, as a result, any use of $env:ProgramFiles to define the location of the modules results in them being installed to potentially a folder that is outside of the control of the installer - to be clear, I mean the PowerShell Core installer, not PowerShellGet.

A further question is whether it will ever be possible to install versions of PowerShell 6 side-by-side or is the currently installed version always upgraded? If so, wouldn't having a Modules folder for each installed version be preferable rather than a shared set of Modules? This is what WindowsPowerShell does with PSCore now - presumably to be a differentiator. **The more I think about it, the more I think using $PSHOME is the wisest choice.**

**Comment by SteveL-MSFT** [comment]
@lwsrbrts thanks for looking into this!  Once 6.0.0 is final, my thinking is that 6.0.x versions are upgrades to 6.0.0 while 6.1.0 would have an option in the installer to be side-by-side (need to see if this is actually possible).   Alternatively, all msi installed versions are upgrades and side-by-side is only supported via the .zip which means it could be put anywhere.

However, most modules shouldn't care if they are running 6.0.0, 6.1.0, or 6.x.0 so I think having them in the shared Modules by default should work for most users.  Perhaps we should add more options to `-scope` so the user can override: `-SharedSystem`

**Comment by bmanikm** [comment]
Updated AllUsers scope install location on PWSH to the parent of $PSHOME. https://github.com/PowerShell/PowerShellGet/pull/196.
