### ISSUE TITLE
Custom installation path

### ISSUE THREAD

**Issue by 0NG** [PowerShell/PowerShellGetv2#224]
In the [document](https://docs.microsoft.com/en-us/powershell/gallery/psget/module/psget_install-module), I cannot find any way to install modules into a custom directory when using Install-module. Is there any way, or is it going to allow users to custom the installation paths of modules like [PsGet](https://github.com/psget/psget)?

**Comment by bmanikm** [comment]
@0NG You will have to use the [Save-Module](https://docs.microsoft.com/en-us/powershell/gallery/psget/module/psget_save-module) cmdlet for your scenario.

**Comment by 0NG** [comment]
@bmanikm Right, Save-Module provides the Path option. But using Save-Module means that I cannot use Update-Module and Uninstall-Module to manage those modules. I think it would be better if Install-Module allows us to customize the installation path.

**Comment by kilasuit** [comment]
@0NG - other than the `AllUsers` path `C:\Program Files\WindowsPowerShell\Modules\` and `CurrentUser` paths `C:\Users\<username>\Documents\WindowsPowerShell\Modules`  what real benefit would this bring? (these are the Windows PowerShell locations, Powershell Core on Windows and on other os's are different)

I'm trying to understand the use case for this outside of the current implementation which for performance reasons uses these two locations, not just for PowerShellGet but also generally for PowerShell itself.

**Comment by 0NG** [comment]
@kilasuit Hi, thanks for your reply! The benefit is **portable**. With this feature, some portable softwares, such as cmder, can manage their PS modules easily. However, now, I am considering if softwares should manage their modules by themselves, and if PsGet should re-impletement some features that PowerShellGet already have.

**Comment by SydneyhSmith** [comment]
Closing this issues as inactive, will re-open if this is still a feature request

**Comment by mlanderos** [comment]
Hi @kilasuit , @SydneyhSmith ,

I was looking for the same functionality and disappointed that no custom location is supported (or I have not found one if it is now supported). We keep our root drives relatively small and currently have our custom PS modules installed on a different drive\directory. I want flexibility in choosing a custom path when I use Install-Module. 

I was looking into updating our package management solution and was hoping to use PowerShellGet/PackagementMgmt(OneGet), but not having the option for a custom install directory halts my decision. I even went as far as temporarily modifying the $env:ProgramFiles variable prior to calling Install-Module so that it can install modules to a different drive location, but then noticed that it appends \WindowsPowerShell\Modules to that path. That is not a huge problem, but I do not want to temporarily modify the $env value every time to make this work.

**Comment by eugenesvk** [comment]
Just adding some activity here in the hopes that @SydneyhSmith will reconsider closing this feature request. @0NG summed up the benefits of a custom installation path nicely
