### ISSUE TITLE
Publish-Script and Publish-Module don't accept proxy parameter

### ISSUE THREAD

**Issue by dlip** [PowerShell/PowerShellGetv2#225]
Publish-Script and Publish-Module don't accept proxy parameter to pass onto Install-NuGetClientBinaries so the command fails behind corporate proxy

## Expected Behavior
Can use proxy with functions that depend on nuget

## Current Behavior
Can't pass proxy

## Possible Solution
Add parameters to these functions

**Comment by VerdonTrigance** [comment]
Agree

**Comment by SydneyhSmith** [comment]
@dlip could you please post the steps to reproduce so that we can better understand what is causing this issue?

**Comment by SydneyhSmith** [comment]
Closing as in-active will re-open if this is still an issue

**Comment by Stephanevg** [comment]
Hi @SydneyhSmith 
I would recommend we reopen this one. This was not a bug, but simply a comment saying that it is not possible to transmit proxy settings when publishing a module since the cmdlet doesn't has the -Proxy parameter.
I face the same limitation today, I think adding this one in the design of powershellGet 3.0 would make sense.

**Comment by bateskevin** [comment]
Please reopen this! This is definitly still an issue.
