### ISSUE TITLE
PowerShellGet functions do not call the latest PackageManagement functions after install

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/PowerShellGetv2#227]
## Expected Behavior
User follows documentation to install PowerShellGet.
User then attempts to use a PowerShellGet command such as Install-Module.
Should not throw error.

## Current Behavior
PowerShellGet calls currently loaded instance of PackageManagement, not the newly installed version.
Since PowerShellGet 1.6.0 leverages new parameters introduced in PackageManagement 1.1.7.0, PackageManagement version 1.0.0.1 that is included in Server 2016 throws an error that AllowPreReleaseVersions is not a valid parameter.

## Possible Solution
Include a common private function to make a static reference to the latest version of the PackageManagement module.

## Steps to Reproduce (for bugs)
See Current Behavior section

## Context
Build pipeline for DSC configurations

## Your Environment
Server 2016
WMF 5.1

**Comment by bmanikm** [comment]
@mgreenegit Please take a look at the documented steps at below URL
https://docs.microsoft.com/en-us/powershell/gallery/psget/get_psget_module#for-systems-with-powershell-50-or-newer-you-can-install-the-latest-powershellget

User has to `exit` the current session after installing the latest version of PowerShellGet. This is required for using the latest version of PackageManagement module so that latest PowerShellGet provider will also be loaded.

Always using the latest version is not a right solution as PackageManagement module gets loaded as per the dependency module requirements specified in the PowerShellGet module manifest.

In automation scripts, to update the PowerShellGet module version, please use the below script. 
Also ensure that PowerShellGet and PackageManagement modules are not imported explicitly, and none of the cmdlets of these two modules are used in the current session prior to invoking the below script.

```powershell
PowerShell -Command { 
    Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.208 -Force; 
    Install-Module –Name PowerShellGet –Force 
}
```

**Comment by mgreenegit** [comment]
Confirmed if I only run those commands this is working.  The important thing I changed is in regards to this: 

>  none of the cmdlets of these two modules are used in the current session prior to invoking the below script
