### ISSUE TITLE
install-module requires UpperCase response to prompt

### ISSUE THREAD

**Issue by mi-hol** [PowerShell/PowerShellGetv2#314]
## Expected Behavior
response to prompts can be any case because 
PowerShell is by design case-insensitive, 
## Current Behavior
The prompts for install-module are required to be in  UpperCase. This is an inconsistent behavior.
## Possible Solution
Allow lower case response

## Steps to Reproduce (for bugs)
![uppercasepromptrequired](https://user-images.githubusercontent.com/22799428/44488724-c445a980-a659-11e8-905d-40ad94bcd879.PNG)

## Your Environment

```PowerShell

> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Linux 4.4.0-17134-Microsoft #137-Microsoft Thu Jun 14 18:46:00 PST 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by edyoung** [comment]
Hi @mi-hol . I haven't been able to reproduce your issue so far. It's strange, because Install-Module uses the same code as every other powershell cmdlet to prompt for confirmation. A couple of questions:

1) Are you maybe running in a different culture? Run Get-Culture to see. Possibly that might have an effect.

2) You could try to do something else which generates a confirmation prompt, for example: 
```powershell
Set-Content c:\foo.txt -Value "hi" ; $ConfirmPreference="low"; Remove-Item c:\foo.txt
```
That should ask for confirmation. If you see the same case-sensitive behavior the issue is not related to Install-Module specifically.

**Comment by mi-hol** [comment]
Thanks @edyoung the proposed verification confirms a different root cause.
I used WSL defaults.
Any idea on the solution?

![2018-08-24 10_10_23-window](https://user-images.githubusercontent.com/22799428/44573406-d1ac8200-a786-11e8-984b-40f4dbd57f1c.png)

**Comment by edyoung** [comment]
I was able to reproduce this in powershell 6.1 preview on WSL with Ubuntu 18.04
```
Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Linux 4.4.0-17134-Microsoft #137-Microsoft Thu Jun 14 18:46:00 PST 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

But not by using the preview or current release bits on ubuntu 17.04.

Unfortunately I don't know why. I'll try and investigate further, but could you please file a bug in the powershell/powershell repo, since that's where the bug seems to be? Any other info you can add (like whether this shows up with other builds of powershell, on other linux distributions, etc, would be very helpful. Thanks!

**Comment by mi-hol** [comment]
moved issue to https://github.com/PowerShell/PowerShell/issues/7639
