### ISSUE TITLE
[SILENT FAILURE] Import-Module MyModule -Verbose writes nothing, does nothing

### ISSUE THREAD

**Issue by jzabroski** [PowerShell/PowerShellGetv2#321]
Here is YET ANOTHER silent failure!
```powershell
PS C:\source> Find-Module -Name MyCompany.PowerShell.SqlClone
```
```
Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.0.0                MyCompany.PowerShell.SqlClone           MyCompany-PowerShell     MyCompany.PowerShell.SqlClone
1.0.0                MyCompany.PowerShell.SqlClone           MyCompany-Development    MyCompany.PowerShell.SqlClone
```
```powershell
PS C:\source> Find-Module -Name MyCompany.PowerShell.SqlClone | % { Get-Command -Module "$_" }
PS C:\source>
```
returns no output

```
PS C:\source> Import-Module MyCompany.PowerShell.SqlClone -Verbose
PS C:\source>
```
returns no output

I have NO IDEA why this is not working.  It was literally working last week.  But it sure doesn't help that -Verbose does NOTHING.

Check this out:

```powershell
PS C:\source> Find-Module -Name MyCompany.PowerShell.SqlClone | % { Get-Command -Module "$_" -Verbose }
PS C:\source> install-module -Name MyCompany.PowerShell.SqlClone -Repository MyCompany-Development

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from 'MyCompany-Development'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
WARNING: Version '1.0' of module 'MyCompany.PowerShell.SqlClone' is already installed at 'C:\Program Files\WindowsPowerShell\Modules\MyCompany.PowerShell.SqlClone\1.0'. To install version '1.0.0', run Install-Module and add the -Force parameter, this command will install
version '1.0.0' side-by-side with version '1.0'.
```

**Comment by jzabroski** [comment]
Here is even more 👍

```powershell
PS C:\source> install-module -Name MyCompany.PowerShell.SqlClone -Repository MyCompany-Development -Force
PS C:\source> Find-Module -Name MyCompany.PowerShell.SqlClone | % { Get-Command -Module "$_" -Verbose }
PS C:\source> import-module MyCompany.PowerShell.SqlClone
PS C:\source> get-command *clone*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        New-VirtualDiskClone                               2.0.0.0    Storage
Cmdlet          Connect-SqlClone                                   2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          Export-DfsrClone                                   2.0.0.0    DFSR
Cmdlet          Get-DfsrCloneState                                 2.0.0.0    DFSR
Cmdlet          Get-SqlClone                                       2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          Get-SqlCloneBackupLocation                         2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          Get-SqlCloneImage                                  2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          Get-SqlCloneImageLocation                          2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          Get-SqlCloneMachine                                2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          Get-SqlCloneSqlServerInstance                      2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          Get-SqlCloneTemplate                               2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          Import-DfsrClone                                   2.0.0.0    DFSR
Cmdlet          New-ADDCCloneConfigFile                            1.0.0.0    ActiveDirectory
Cmdlet          New-SqlClone                                       2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          New-SqlCloneImage                                  2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          New-SqlCloneMask                                   2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          New-SqlCloneSqlScript                              2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          New-SqlCloneTemplate                               2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          Remove-SqlClone                                    2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          Remove-SqlCloneImage                               2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          Remove-SqlCloneMachine                             2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          Remove-SqlCloneTemplate                            2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          Rename-SqlCloneImage                               2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          Reset-DfsrCloneState                               2.0.0.0    DFSR
Cmdlet          Reset-SqlClone                                     2.7.3.426  RedGate.SqlClone.Powershell
Cmdlet          Wait-SqlCloneOperation                             2.7.3.426  RedGate.SqlClone.Powershell
```

```powershell
PS C:\source> ls "C:\Program Files\WindowsPowerShell\Modules\MyCompany.PowerShell.SqlClone\1.0"


    Directory: C:\Program Files\WindowsPowerShell\Modules\MyCompany.PowerShell.SqlClone\1.0


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        8/13/2018  10:27 PM           1886 Get-BuildCloneImageStatus.ps1
-a----        8/13/2018  10:27 PM             93 Get-ScriptDirectory.ps1
-a----        8/13/2018  10:27 PM           1159 Get-SvnRootDirectory.ps1
-a----        8/13/2018  10:27 PM            606 Install-SqlCloneCmdlets.ps1
-a----        8/13/2018  10:27 PM           1888 New-MyCompanySqlClone.ps1
-a----        8/13/2018  10:27 PM           1442 New-MyCompanySqlCloneImage.ps1
-a----        8/29/2018   5:13 PM           3491 Sync-SqlCloneCmdlets.ps1
-a----        8/13/2018  10:27 PM            293 Update-MyClone.ps1
-a----        8/29/2018   4:51 PM            593 Update-Library.ps1
-a----        8/30/2018  10:43 PM           8070 MyCompany.PowerShell.SqlClone.psd1
-a----        8/13/2018  10:27 PM            746 MyCompany.PowerShell.SqlClone.psm1
```

**Comment by edyoung** [comment]
John, sorry you've been having so much trouble. 

Without access to your module or repository setup, I can't be 100% confident about the issue, but I hope this helps a bit.

Taking this one item at a time.

1)

```powershell
 Find-Module -Name MyCompany.PowerShell.SqlClone | % { Get-Command -Module "$_" }
```

Find-Module is part of PowerShellGet. It searches your registerered repositories and returns info on what's available to install. 

Get-Command is part of PowerShell, rather than PowerShellGet. Get-Command -Module foo searches the modules *already installed* on the machine, and returns the commands in that module. So Get-Command -Module MyCompany.PowerShell.SqlClone will return the commands in that module if it is installed, but not the commands from a module which is in a repository but not installed yet.

Get-Command -Module xyz , where xyz is not installed on the system, returns no output rather than raising an error. (Same for Get-Module xyz.) You could quite reasonably claim that is a bug, but I doubt it can be changed because it would break backward compatibility. If you would like to file a bug on that, it should go in the PowerShell repo rather than PowerShellGet.

Finally, $_ is the whole object, and "$_" gives the .ToString() of that object. The string representation of the module name is not the module's name, but contains more data, eg:

```powershell
PS C:\Users\edwin> Find-Module -Name AzureRM.Profile | % {"$_"}
@{Name=AzureRM.profile; Version=5.5.1; Type=Module; ...}
```

So this command doesn't produce any output because it tries to find the commands in a module called "@{Name=MyCompany.PowerShell,SqlClone..." which is not present on your computer.

To find the set of cmdlets in a module in a repository without installing it, run

```powershell
(Find-Module -Name AzureRM.Profile).AdditionalMetadata.Cmdlets
```

2)
```powershell
Import-Module MyCompany.PowerShell.SqlClone -Verbose
```

Import-Module is part of PowerShell, not PowerShellGet. It loads a module already installed on your computer into the running Powershell instance. In general -Verbose should list the cmdlets and functions exported by the module. You could see this succeed silently if you have a module with no exports. Try running Get-Module MyCompany.PowerShell.SqlClone after this - if you see it in the output, it was loaded. 

In general, attempting to import a module which is not installed or is invalid will produce an error. It's possible there is a case where this does not happen, and I would consider that a bug, but we'd need more info to isolate it if so. If you could share a cut-down version of the module which illustrates the problem that would help.

3) I think this is explained by (1) above.

4) The main question here is why no Clone commands from the SqlClone library are shown. I think the most likely explanation is that they are not being exported from the module. Try running 

```powershell
Import-Module MyCompany.PowerShell.SqlClone
Get-Module MyCompany.PowerShell.SqlClone
Get-Module MyCompany.PowerShell.SqlClone | select -exp ExportedCommands
```

If module is loaded but the command list is empty, you need to look at the manifest to see why nothing is exported. If the module is not loaded and there is no error printed, I think there is a bug in Import-Module which we should look into.

**Comment by bmanikm** [comment]
Some additional thoughts which may help you in the investigation:

- Run Test-ModuleManifest with the module manifest path to verify the exported commands
```powershell
Test-ModuleManifest -Path 'C:\Program Files\WindowsPowerShell\Modules\MyCompany.PowerShell.SqlClone\1.0\MyCompany.PowerShell.SqlClone.psd1' -Verbose
```
- Review the dot sourcing logic in MyCompany.PowerShell.SqlClone.psm1 for exporting the functions in individual script files.

- Verify the values of RootModule, NestedModules and FunctionsToExport entries in the MyCompany.PowerShell.SqlClone.psd1 

- Try importing the .psm1 file using below command
```powershell
Import-Module 
'C:\Program Files\WindowsPowerShell\Modules\MyCompany.PowerShell.SqlClone\1.0\MyCompany.PowerShell.SqlClone.psm1' -Verbose 
```

**Comment by jzabroski** [comment]
@edyoung  Thanks, this appears to have pointed me deeper down a rabbit hole.

I created my psd1 file with `New-ModuleManifest -Path MyCompany.PowerShell.SqlClone.psd1`
As it turns out, this is a pretty awful cmdlet and is yet another layer of issues I have encountered.
The file it generates is basically obsolete, according to this post by Kirk Munro: https://github.com/PowerShell/PSScriptAnalyzer/issues/428#issuecomment-173677887

I'll have to dig further, but I am not exactly impressed with the overall design of PowerShell's module system or PowerShellGet.  Here is what `Get-Help New-ModuleManifest` returns for me - nowhere does it say RootModule is deprecated. I'm not even sure that's my problem, but I tried deliberately setting `PowerShellVersion = '3.0'` and `Test-ModuleManifest` did not yell at me. It looks like `RootModule` and `ModuleToProcess` are both supported.

Finally, digging further, I notice that when I Test-ModuleManifest, I'm seeing bizarre behavior that only seems to happen after making numerous edits to the psd1 file. As I continue to make small edits, eventually Test-ModuleManifest stops working. (I swear I have never done drugs in my life, and I am not hallucinating.)

```powershell
 $result = Test-ModuleManifest C:\source\Infrastructure\SqlClone\Powershell\MyClone.PowerShell.SqlClone\MyClone.PowerShell.SqlClone.psd1 -Verbose
```

I then opened a new PowerShell window, without making any further changes, and then typed the following (output inline):

```powershell
PS C:\WINDOWS\system32>  $result = Test-ModuleManifest C:\source\Infrastructure\SqlClone\Powershell\MyCompany.PowerShell.SqlClone\MyCompany.PowerShell.SqlClone.psd1 -Verbose
WARNING: The module manifest member 'ModuleToProcess' has been deprecated. Use the 'RootModule' member instead.
VERBOSE: Loading module from path 'C:\source\Infrastructure\SqlClone\Powershell\MyCompany.PowerShell.SqlClone\MyCompany.PowerShell.SqlClone.psm1'.
PS C:\WINDOWS\system32>  $result = Test-ModuleManifest C:\source\Infrastructure\SqlClone\Powershell\MyCompany.PowerShell.SqlClone\MyCompany.PowerShell.SqlClone.psd1 -Verbose
VERBOSE: Loading module from path 'C:\source\Infrastructure\SqlClone\Powershell\MyCompany.PowerShell.SqlClone\MyCompany.PowerShell.SqlClone.psm1'.
PS C:\WINDOWS\system32> $result

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0        MyCompany.PowerShell.SqlClone           {Update-PandaLibrary, Update-MyClone, Get-SvnDirectory}
```

I apologize if this post seems a bit like a diary, but I'm getting tired/worn down debugging PowerShell core issues.  You can say that some of these functions are PowerShell core and PowerShellGet is not core, but at the end of the day, you guys are Microsoft employees. This is like saying the CLR and mscorlib are two different things and that AssemblyVersionAttribute doesn't have to have tangible meaning.  If the results from Test-ModuleManifest are not consistent. A google for "[Test-ModuleManifest side effect](https://www.google.com/search?q=test-modulemanifest+side+effect)" yields no results.

**Comment by jzabroski** [comment]
Here is something interesting.  From the previous shell I had open (where I suspected it had some "side effect" in my session):

```powershell
PS C:\WINDOWS\system32>  $result = Test-ModuleManifest C:\source\Infrastructure\SqlClone\Powershell\MyCompany.PowerShell.SqlClone\MyCompany.PowerShell.SqlClone.psd1 -Verbose
VERBOSE: Loading module from path 'C:\source\Infrastructure\SqlClone\Powershell\MyCompany.PowerShell.SqlClone\MyCompany.PowerShell.SqlClone.psm1'.
PS C:\WINDOWS\system32> $result

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0        MyCompany.PowerShell.SqlClone           {Update-Library, Get-SvnDirectory}


PS C:\WINDOWS\system32> Uninstall-Module MyCompany.PowerShell.SqlClone -Verbose
VERBOSE: Performing the operation "Uninstall-Module" on target "Version '1.0' of module 'MyCompany.PowerShell.SqlClone'".
VERBOSE: Successfully uninstalled the module 'MyCompany.PowerShell.SqlClone' from module base 'C:\Program Files\WindowsPowerShell\Modules\MyCompany.PowerShell.SqlClone\1.0'.
PS C:\WINDOWS\system32>  $result = Test-ModuleManifest C:\source\Infrastructure\SqlClone\Powershell\MyCompany.PowerShell.SqlClone\MyCompany.PowerShell.SqlClone.psd1 -Verbose
WARNING: The module manifest member 'ModuleToProcess' has been deprecated. Use the 'RootModule' member instead.
VERBOSE: Loading module from path 'C:\source\Infrastructure\SqlClone\Powershell\MyCompany.PowerShell.SqlClone\MyCompany.PowerShell.SqlClone.psm1'.
PS C:\WINDOWS\system32>  $result = Test-ModuleManifest C:\source\Infrastructure\SqlClone\Powershell\MyCompany.PowerShell.SqlClone\MyCompany.PowerShell.SqlClone.psd1 -Verbose
VERBOSE: Loading module from path 'C:\source\Infrastructure\SqlClone\Powershell\MyCompany.PowerShell.SqlClone\MyCompany.PowerShell.SqlClone.psm1'.
PS C:\WINDOWS\system32> $result

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0        MyCompany.PowerShell.SqlClone           {Update-Library, Update-MyClone, Get-SvnDirectory}
```
How on God's green earth uninstalling 1.0 from my profile path effects the result of Test-ModuleManifest in my local development folder.... ARGGGGGGH

You guys.  I am trying very hard to be nice.  Please just stop building new features and just fix bugs.

**Comment by edyoung** [comment]
PowerShell and PowerShellGet are obviously closely related. I'm pointing out the difference because they have separate GitHub projects and issues databases. Since Test-ModuleManifest is in PowerShell, other bug reports concerning it are there ( https://github.com/PowerShell/PowerShell/issues?utf8=%E2%9C%93&q=is:issue+is:open+test-modulemanifest) and filing an issue there is the best way to get a resolution. I'd be happy to port a clear bug over, but I'm not sure I can effectively summarize this one.

If you can narrow down the repro to something like "Here's test.psd1; when I run Test-ModuleManifest on it twice, I only get warnings the first time" it'll be a lot easier to isolate the issue and fix it. I have tried running Test-ModuleManifest on the same file several times, and running it on a manifest while another version of the same module is installed, but have not been able to reproduce either problem.

**Comment by jzabroski** [comment]
I believe the issue is related to the poor design of Test-ModuleManifest
depending on ModuleCmdletsBase.cs

I recommend the Powershellget team write their own manifest tester and RIP
out all references to PowerShell core, as PowerShellGet is internally using
bad and unreliable code. The link you provided shows how bad
Test-ModuleManifest is: as a Library author, I would not take dependency on
a poorly written function/class.

**Comment by edyoung** [comment]
While I understand your point of view, I am reluctant to write another separate module tester, because both would need to be maintained in future and the buggy implementation would still exist in PowerShell itself. At this point I am going to close this issue because the linked bug tracks the Test-ModuleManifest problem, and this bug doesn't track an actionable issue to fix in PowerShellGet itself. Let me know if you disagree.
