### ISSUE TITLE
.git folders being included in some uploaded modules

### ISSUE THREAD

**Issue by edyoung** [PowerShell/PowerShellGetv2#378]
Many packages (https://www.powershellgallery.com/packages/DosInstallUtilities.Menu/2.15 for example) contain .git folders. Looks like these are not being filtered out by the dotnet or nuget commands being used for publishing. We could copy all the files to be published to a new temp dir and leave out all the files which should be ignored (files starting with . or with hidden attribute on windows).

**Comment by iricigor** [comment]
I am not really an expert, but can this behaviour be changed with [nuspec](https://github.com/PowerShell/PowerShellGet/blob/4f05c7f0ef101b48b810848b4be17dc42f6ac4ee/src/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1#L402) settings?

**Comment by alerickson** [comment]
@iricigor I'm not sure you can change that behavior in the nuspec.  In any case, I think it'd be more straightforward and consistent with previous behavior to leave out ignore files before publishing, particularly because the script or module is being copied to a temp directory [before being passed on](https://github.com/PowerShell/PowerShellGet/blob/4f05c7f0ef101b48b810848b4be17dc42f6ac4ee/src/PowerShellGet/public/psgetfunctions/Publish-Module.ps1#L598) to Publish-PSArtifactUtility anyway.

**Comment by CJHarmath** [comment]
@kwirkykat  I've forked PowerShellGet and added a feature to support .psgetignore as a proof of concept and tested it with xWebAdministration and it seems to be working fine.

The idea is to add support for a .psgetignore file which is checked by Publish-ModuleArtifacts then passed into PowerShell's Get-ChildItem -Exclude. 

```
# Copy the module into the dist folder
    # Check if there is a .psgetignore file and exclude those files
    if (Test-Path -Path $PsGetIgnore) {
        # read .psgetignore excluding lines with comments and empty lines
        $exclude = Get-Content -Path $PsGetIgnore | Where-Object {
            !$_.Trim().StartsWith("#") -and $_.Trim() -ne ""
        }
        Get-ChildItem -Path $ModuleRoot -Exclude $exclude | Copy-Item -Recurse -Destination $ArtifactRoot
    }
    else {
        Copy-Item -Path $ModuleRoot -Destination $ArtifactRoot -Recurse
    }
```

Another approach could be to generate the .psgetignore into the nuspec file, but as soon as I saw that there is a copying already to a temp folder I though that the copy step itself could just ignore the unnecessary files.

```
  <contentFiles>
        <!-- Exclude Content -->
        <files exclude=".git*"/>
        <files exclude=".vscode*"/>
    </contentFiles>
```


This could also solve the issue here
https://github.com/PowerShell/PowerShellGet/issues/191

I haven't made a pull request but the change can be found here
https://github.com/csharmath/PowerShellGet/blob/dea35d51139c7568d9cf78909d1e95847084bbc4/tools/build.psm1#L399

Assuming this is a good idea and I can get approved to sign a CLA at my company, I am happy to tweak as necessary and submit a PR, but also happy if someone implements something similar especially if that's quicker.

**Comment by CJHarmath** [comment]
I would probably also be a good idea to maintain a default ignore list with .git .vscode so those folders are never getting packaged up

**Comment by alerickson** [comment]
@csharmath Publish-ModuleArtifacts is specifically for the build process of PowerShellGet, we'd want to make changes in the[ Publish-Module](https://github.com/PowerShell/PowerShellGet/blob/4f05c7f0ef101b48b810848b4be17dc42f6ac4ee/src/PowerShellGet/public/psgetfunctions/Publish-Module.ps1#L395)/Script cmdlets.

**Comment by CJHarmath** [comment]
@alerickson  thanks for pointing that out.
I've only tested parts of that function not the whole thing, so I didn't realize that I was editing the wrong function. ugh

I've updated the fork to modify the Publish-Module

https://github.com/csharmath/PowerShellGet/blob/f7260892e4a225e5714840937c9f7cc9d893c18b/src/PowerShellGet/public/psgetfunctions/Publish-Module.ps1#L369

Before I make further changes, just wanted to clarify if this is something you guys would consider adding as a feature?
Also, would .psgetignore be right name for this?

**Comment by edyoung** [comment]
Sorry for the delay. Sure, would be willing to include - however what puzzles me a bit is why this has regressed. I believe it relates to the version of nuget.exe or dotnet which is being called while publishing. If we can work out how to get back to the prior behavior that might be simpler and wouldn't require managing .psgetignore etc.

**Comment by edyoung** [comment]
I think the simplest option is to always skip hidden files and directories. I have a change that should do that almost ready to go.

**Comment by iricigor** [comment]
How would it treat not hidden files starting with a dot? Would it be the same on Windows and Linux?

**Comment by edyoung** [comment]
@iricigor  wrote:

How would it treat not hidden files starting with a dot? Would it be the same on Windows and Linux?

Good question. Current PR leans on the implementation of get-childitem,
which differs between Windows and Linux following the OS conventions. On
Linux, there is no hidden attribute as far as I know, so files starting
with a dot will be hidden. On Windows, Get-ChildItem uses the hidden
attribute but will include files starting with a dot otherwise.

It would be possible to leave out files & directories starting with . on
Windows as well. I'm not quite sure whether that is the right thing to do...

**Comment by edyoung** [comment]
@csharmath Don't mind considering a more complete approach with configurable ignore file if you want to propose one. But wanted to fix the default behavior first.

**Comment by IamFive** [comment]
I think add a  `.**ignore` config file is a good idea.
