### ISSUE TITLE
Set-PSRepository removes trailing / on SourceLocation 

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PowerShellGetv2#401]
Opening from twitter https://twitter.com/PrzemyslawKlys/status/1085647512508059649
Setting the PS Gallery to "Trusted" or "Default" removes the trailing \ on source location causing the repository to not be found at Install-Package

**Comment by alexandair** [comment]
Causing the repository to be not be found at Update-Module.

**Comment by edyoung** [comment]
I think the issue is subtly different, but it's possible I am missing something. 
```powershell
Set-PSRepository PSGallery -InstallationPolicy Trusted 
```

resets the SourceLocation to the built-in value, which is https://www.powershellgallery.com/api/v2 (no trailing /). But Register-PSRepository -Default also sets the value to https://www.powershellgallery.com/api/v2 . The question is what previously set the repository url to https://www.powershellgallery.com/api/v2/ (with a trailing /). See also #349

**Comment by alexandair** [comment]
If the URL without a trailing / is the built-in value, why does Update-Module ask for an URL with the trailing /?

```powershell
PS C:\> update-module powershellget -verbose
VERBOSE: Checking for updates for module 'PowerShellGet'.
PackageManagement\Install-Package : Unable to find repository 'https://www.powershellgallery.com/api/v2/'.
Use Get-PSRepository to see all available repositories.
```

**Comment by edyoung** [comment]
The url which was used at initial install time is saved, and then used again at update time. If no repository matching the saved url is found at that time, you see this error.

**Comment by edyoung** [comment]
See comments on PR above. This does NOT change the behavior of Set-PSRepository but I believe it resolves the Update-Module problem.
