### ISSUE TITLE
[Feature] Do not update to major version of modules with Update-Module unless explicly passed a -IncludeMajorVersion parameter

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShellGetv2#422]
Currently `Update-Module` will update Major versions as well as minor versions of modules. 

This is a bad design practice and as such should not be the default action and instead should be only allowed as part of another, explicitly passed Parameter flag when calling the Update-Module function

**Comment by edyoung** [comment]
I understand the ask, but I don't think I agree. We already have numerous issues with people complaining that PowerShellGet commands are 'too cautious' and require too many extra flags (-Force, -AllowClobber, etc) and I'm pretty reluctant to add a new one. Open to argument pro-or-con from the community, please add comments here. 

Some other thoughts:
- A possible alternative would be to leave the default and add a -MinorOnly flag opting in to this behavior.
- How consistent are people about major version numbers indicating breaking changes?
- Would we want to special-case update from prerelease to release? (0.9-beta1 to 1.0, for example)
- Would a 'pinning' system be used?
- PowerShellGet has 2 major usage cases: managing build dependencies (like nuget) and curating dependencies used interactively in a shell. My hunch is that this change is useful for the former but less useful for the latter.

**Comment by kilasuit** [comment]
Updating should only ever allow a minor update to occur without requiring User interaction as these **Should** not have breaking changes in them & if PowerShellGet was to more accurately enforce that notion then you would have a more robust and trusted system in place that would make it better for educating end authors into the differences in Major & Minor versioning.

Pre-Release to Release is same usecase as Minor to Major IMO 

My view is that this helps in both former and latter use cases as I personally would expect that version 2.11 -> 2.16 should allow me to easily upgrade with no/little impact to existing scripts and for interactive use, where as 3.1 may introduce many braking changes that I would need to test prior to pushing out those versions to all systems that use that particular product.

    * A possible alternative would be to leave the default and add a -MinorOnly flag opting in to this behavior.

I'm not sure that I agree this makes sense as I would expect that PSGet would be the enforcer of better practices and this to me feels backwards (like the installation of modules defaulting to AllUsers dir not CurrentUser Dir which was a wrong decision)

**Comment by Jaykul** [comment]
I agree with @edyoung:

1. Update-Module installs new versions of modules side-by-side. This should not break things. If it does, **those things are wrong,** not PowerShellGet.
2. RequiredModules support min/max versions for dependencies. THAT is how you (module authors) can prevent breakage.
3. If PowerShellGet doesn't update to the latest automatically, people will never update.
4. If there's another switch you have to set to `-ReallyUpgradeAllTheThingsDangIt` I'm just going to teach everyone to put it in their PSDefaultParameterValues 😜 

Under your plan, we would need PowerShellGet to check for major updates _and **warn** about them_, while simultaneously installing minor updates. Otherwise, people would never know the new versions were available.

## Document which version of the module works in your scripts and modules

The only way that a new major version of a module dependency can break your script or module is if you don't have a documented MaximumVersion in your `#requires` statements or `RequiredModules`. That's the education we need: for people to start documenting their dependencies semantically.

I do like the idea of a robust -IncludePatches mode, where we'd install the latest minor/patch versions for every major version you have installed, _as well as_ new major versions, to make sure we pick up the latest bug fixes for modules which are doing the right thing. But it's not going to help if people aren't specifying max versions.  

P.S. what we really need is _exclusive_ max version (i.e. min = 1.4.0, max = 2.0 should have meant that I can't use 2.0 -- the way it is now, I have to specify max = 1.999.999 which is just silly)

**Comment by natescherer** [comment]
I think the biggest blocker around having Update-Module only do minor updates is that there's no surefire way to tell what is a minor or major update. The Gallery doesn't require SemVer, and private NuGet feeds certainly don't, and without an across-the-board versioning scheme, there's no way to be sure if a module that went from 1.2.3 to 2.0.0 was ACTUALLY due to a breaking change or just because the dev felt like bumping the number.

**Comment by edyoung** [comment]
We don't plan to implement this, so closing to clear the decks. If you have a strong case for this or a similar feature, feel free to comment here and/or reopen.
