### ISSUE TITLE
Cannot publish module with a pre-release dependency

### ISSUE THREAD

**Issue by matteo-prosperi** [PowerShell/PowerShellGetv2#517]
I have published a module with the following version numbering
```
    # Module manifest for module 'MyBaseModule'
    ModuleVersion = '3.3.500'

    GUID = '0f1488f1-241b-4a0c-80cc-9f3f69d81818'

    PrivateData = @{
        PSData = @{
            Prerelease = 'beta0'
        }
    }
```
This shows upon the gallery as version `3.3.500-beta0`,  as expected.
When I try to `Publish-Module` for a second module which is dependent on the first
```
    # Module manifest for module 'MyDependentModule'

    RequiredModules = @(
        @{
            ModuleName = 'MyBaseModule';
            RequiredVersion = '3.3.500';
            Guid = '0f1488f1-241b-4a0c-80cc-9f3f69d81818' }
    )

    ModuleVersion = '3.3.500'

    PrivateData = @{
        PSData = @{
            Prerelease = 'beta0'
        }
    }
```
I get an error complaining that `MyBaseModule` is not available on the gallery.
It is worth noting that the modules actually import correctly when used locally.

If I try to change the `RequiredVersion` to
```
            RequiredVersion = '3.3.500-beta0';
```
then `Publish-Module` gives me an error saying that '3.3.500-beta0' is not a valid version number.

**Comment by viralmodi** [comment]
@SteveL-MSFT @matteo-prosperi  We are seeing this same issue about unable to Install or Publish pre-release modules which depend on other pre-release modules. Is there any resolution to this? If not, what are the possible workarounds?

**Comment by alerickson** [comment]
@viralmodi linking to [this issue](https://github.com/PowerShell/PowerShellGet/issues/85) regarding a workaround for publish. 

What module are you trying to install?  I'd like to test if there's a work around for this but can't easily find a module with a prerelease dependency.

**Comment by viralmodi** [comment]
@alerickson Its a work-related module internal (pre-release) to our office. It depends on another internal (pre-release) module. I can't share any of it. You could create a couple of helloworld modules, add pre-release tags, make one dependent on another by adding a manifest file and test it.

**Comment by alerickson** [comment]
@viralmodi is the installation for a pipeline/DevOps oriented use?

**Comment by alerickson** [comment]
@viralmodi  do you still have the issue if the dependencies are installed before the module?

**Comment by viralmodi** [comment]
@alerickson We maintain an internal version of our tools and an external version. The internal version or the pre-release version carries pre-release feature which get released as per the release cadence. The employees in our company have access to all pre-release features. Our pre-release versions are tagged as <productname><release version as per semver><-preview.build_id>. Our release versions are tagged as <productname><release version as per semver> This is the use case for which we are facing a problem since some of our pre-release version module is dependent on another pre-release version module.
As for your second question, it doesn't work. It still complaints about "Unable to resolve module dependency"

**Comment by matteo-prosperi** [comment]
@viralmodi I was not able to find a workaround. I simply released the prerelease modules with "normal" versioning marking them as prerelease in the module description.

**Comment by alerickson** [comment]
@viralmodi the current preview release of PowerShellGet v3 should address this issue since we handle semver syntax:  https://www.powershellgallery.com/packages/PowerShellGet/3.0.0-beta3 .
I can't think of any workarounds that would be appropriate for you situation. 

I'm currently working on publishing functionality for v3 as well, so that should be out in the next couple of weeks and address the corresponding issue with publish-module.

**Comment by viralmodi** [comment]
@alerickson Thanks. We will try out the PowerShellGet v3 and let you know. Will wait for your fix in Publish functionality as well.

**Comment by viralmodi** [comment]
@alerickson PowershellGet v3 will be default in which powershell versions? We are thinking of using some other workarounds for versioning of our preview product for internal users so they do not have to rely on PowershellGet v3 install to install our cmdlets.

**Comment by kumbham** [comment]
@alerickson is there an update on the Publish module? I'm still facing the following issue with the latest PowershellGet v3 module.

```powershell
Publish-Module @publishArgs

The 'RequiredModules' member is not valid in the module manifest file '*.psd1': Cannot convert value "System.Collections.Hashtable" to type
      | "Microsoft.PowerShell.Commands.ModuleSpecification". 
Error: "Cannot convert value "0.2.0-1" to type "System.Version". Error: "Input string was not in a correct format.""
```

**Comment by SteveL-MSFT** [comment]
v3 beta10 fixes this issue.  I don't believe we'll spend time fixing this in v2.
