### ISSUE TITLE
Unsigned module error triggers when no signed module is installed

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShellGetv2#96]
Re:  #94 (now closed)

I hope to write about this, but I need to understand it myself. Thanks in advance for your help. 

If I understand correctly, the catalog signing error appears only when:

-- An installed version of the same module **is signed**, but the version that the user is trying to install is not signed. 
-- This signing check is module-specific. 

But, on my VM (Server 2016 RTM, 5.1.14393.693), the installed version of Pester, 3.4.0, does not have a Pester.cat file. However, when I try to install 4.0.2, which also does not have a Pester.cat file, I get the catalog signing error. 

What's going on here?

------------------------------

Also, the error message is very confusing. It refers to the version that is not installed (4.0.2) as the **"previously-installed module 4.0.2"***. That was probably supposed to be the module name, not the version. I'll see if I can track that down and submit a PR.

```
Ensure that the version '4.0.2' of the module 'Pester' has the catalog file 'Pester.cat' and signed with the same publisher 'CN=Microsoft Root Certificate Authority 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' as the previously-installed module '4.0.2' with version '3.4.0' 
under the directory 'C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0'.
```

**Comment by bmanikm** [comment]
Hi @juneb, thanks for submitting a PR for fixing a typo in format!
- Yes, publisher validation is module-specific.
- It is applicable only when the latest version of the module being installed is signed.
- Publisher details are retrieved from either catalog file or module manifest. First, catalog file otherwise module manifest file. For all in-box modules, module manifest is signed.

**Comment by juneb** [comment]
"It is applicable only when the latest version of the module being installed is signed."
[juneb] The error message occurs when the module being installed is **unsigned** and there is a signed version of the module already installed. Why would we throw an error for a signed module?

Also, on my VM (Server 2016 RTM, 5.1.14393.693), the installed version of Pester, 3.4.0, is unsigned. It does not have a Pester.cat file. However, when I try to install 4.0.2, which also does not have a Pester.cat file, I get the catalog signing error. What's going on here?

**Comment by bmanikm** [comment]
"It is applicable only when the latest **installed** version of the module being installed is signed."
Latest version from the installed versions of module are considered for the publisher validation.

In above mentioned case (in your above reply), installed latest version is signed and version being installed is unsigned, right? Since the new version is not signed, publisher validation should fail, correct? what is your expectation?

**Comment by juneb** [comment]
Yes, that's my expectation, but that's not what I'm seeing on my VM.

On my VM, the latest installed version of Pester, 3.4.0, is *unsigned* (no Pester.cat file in the module). In fact, both 3.4.0 and 4.0.2 are unsigned. So, I can't figure out why I'm getting the catalog signature error.

**Comment by bmanikm** [comment]
Please take a look at the third point I mentioned above.
**Publisher details are retrieved from either catalog file or module manifest. First, catalog file otherwise module manifest file. For all in-box modules, module manifest is signed.**

Check the authenticode signature of Pester.psd1 file under 3.4.0 version.

If that module manifest file is not authenticode signed, please provide the -debug output to investigate further.

**Comment by juneb** [comment]
Ah! Now, I see. Thanks. 

So, is this an error in Pester, because the .psd1 in 4.0.2 is unsigned?

**Comment by ghost** [comment]
I've got a draft of catalog signing docs I need to share. Will make sure it's pushed to a viewable repo & share with @June before EOD 3/8

**Comment by juneb** [comment]
Thanks, Keith. That's great. We need some best practice guidance.

**Comment by dotps1** [comment]
Just thought i'd add @juneb, the version of pester on a fresh install of windows 10 does not come from the gallery.  and that is why you cannot just do a `Update-Module -Name Pester`.

**Comment by juneb** [comment]
@dotps1 Thanks, I used Install-Module. 

The .../Pester/3.4.0/* directory does not include a .cat file, but Get-AuthenticodeSignature returns a valid catalog signature. 

But, I don't see one of those long signature blocks in the file. Is the embedded signature in metadata?
